version: '3.1'

services:

  php-fpm:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src/laravel:/var/www/html/laravel
      - ./src/symfony:/var/www/html/symfony
      - ./src/codeigniter:/var/www/html/codeigniter
      - ./src/slim:/var/www/html/slim
      - ./src/yii:/var/www/html/yii
    networks:
      - docker-pnmamhes

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - '80:80'
      - '81:81'
      - '82:82'
      - '83:83'
      - '84:84'
    volumes:
      - ./src/laravel:/var/www/html/laravel 
      - ./src/symfony:/var/www/html/symfony
      - ./src/codeigniter:/var/www/html/codeigniter
      - ./src/slim:/var/www/html/slim
      - ./src/yii:/var/www/html/yii
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-pnmamhes

  db:
    container_name: mysql
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - docker-pnmamhes


  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DESIGN: haeckel
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 33061:8080
    networks:
      - docker-pnmamhes

  mailpit:
    container_name: mailpit
    image: 'axllent/mailpit:latest'
    restart: unless-stopped
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - docker-pnmamhes

  redis:
    container_name: redis
    image: 'redis:7-alpine'
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--bind",
        "0.0.0.0",
        "--appendonly",
        "yes"
      ]
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    volumes:
      - ./docker/redis:/data
    networks:
      - docker-pnmamhes

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment:
      - "ELASTICSEARCH_URL=http://es:9200"
    ports:
      - 5601:5601
    restart: "unless-stopped"
    networks:
      - docker-pnmamhes

  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - docker-pnmamhes

networks:
  docker-pnmamhes:
    driver: bridge
