CREATE DATABASE IF NOT EXISTS laravel;
CREATE DATABASE IF NOT EXISTS laravel_test;

CREATE DATABASE IF NOT EXISTS symfony;
CREATE DATABASE IF NOT EXISTS symfony_test;

CREATE DATABASE IF NOT EXISTS codeigniter;
CREATE DATABASE IF NOT EXISTS codeigniter_test;

CREATE DATABASE IF NOT EXISTS slim;
CREATE DATABASE IF NOT EXISTS slim_test;

CREATE DATABASE IF NOT EXISTS yii;
CREATE DATABASE IF NOT EXISTS yii_test;